### ISSUE TITLE
No changelog for v0.24.0

### ISSUE THREAD

**Issue by odensc** [ranisalt/node-argon2#188]
Hi, I was upgrading my dependencies and saw this module was updated. Since it's `v0.x` there could be breaking changes with updates - so I went to the Releases tab to look for a changelog, but there's none for `v0.24.0`.

I see now that you just removed the minimum memory limit, but would you mind adding a changelog to avoid confusion? It's a bit worrying when I don't know what's changed - especially for a module as important as password hashing.

**Comment by ranisalt** [comment]
You are right, and git should have pushed a tag with the release of v0.24.0, but now I see it didn't.

I want to [keep a changelog](https://keepachangelog.com/en/1.0.0/), though, I just didn't find the time to start it.

**Comment by PineappleIOnic** [comment]
Hey there, I'm happy to help with this if I can get the run down of the changes.

**Comment by ThisIsMissEm** [comment]
@ranisalt I've noticed that there's still no changelog, and may releases aren't tagged in git, nor available as releases on github — this makes upgrading the package with any degree of confidence hard, since I don't necessarily know what's changed.

Let me know if you'd like help setting up a release work flow on GitHub Actions.
