### ISSUE TITLE
inconclusive error while validating non-argon2-hash

### ISSUE THREAD

**Issue by CodingVampyre** [ranisalt/node-argon2#217]
Welcome to the issues section if it's your first time!

### Before creating an issue, please be sure to:
- [X] Checkout to the latest version, **including submodules**
- [X] Try to find an *isolated* way to reproduce the behavior
- [X] Fill in all the blanks in the most specific way you can

### Steps to reproduce
1. include argon2
2. run `argon2.valdiate()` with the first parameter set to a hash that is not argon2-compatible, f.ex. bcrypt-hashes

### Expected behaviour
* Should throw an error pointing out that the provided string is not a valid hash OR
* just return `false` (better, in my opinion)

### Actual behaviour
throws an error similar to 
> `TypeError: Cannot destructure property `m` of 'undefined' or 'null'.`

### Environment
**Operating system**: MacOS

**Node version:** v12.6.0

**Compiler version:** clang, current

**Comment by rogeriopvl** [comment]
I'm also having this issue in a docker container running latest ubuntu.

I can't reproduce it locally on OSX tho.

**Comment by ranisalt** [comment]
Why are you trying to validate non-argon2 hashes with argon2? This library refuses to do so as I assume this should never happen.

**Comment by rogeriopvl** [comment]
@ranisalt in my case, I was refactoring an auth service to use argo2 instead of bcrypt, and the database migrations script had an admin user with a bcrypt hash hardcoded. After deploying the refactor, this caused argon to throw that cryptic error message when trying to login with the admin user.

I know I shouldn't be using non-argon passwords with argon, but if argon returned a more useful message, or even `false` it would make finding this problem a lot easier.

**Comment by ranisalt** [comment]
You should wrap the call to `verify` with a try/catch statement anyway, as this library returns true/false for proper hashes only, and throws on several calculation issues (lack of memory, for instance). That is just one of the issues that a try/catch block would solve.

If you want better error messages, wrap [this line](https://github.com/ranisalt/node-argon2/blob/master/argon2.js#L55) with a try/catch statement and rethrow a better message, and I'll consider merging.
