### ISSUE TITLE
Educate users about pre-built binaries and/or recommend always building from source

### ISSUE THREAD

**Issue by daniel-j-h** [ranisalt/node-argon2#245]
Hey hey, great bindings you have here, thanks a lot for doing awesome work! :1st_place_medal: :hugs: 

I was curious how you provide pre-built binaries and looked a bit into it.

It seems like you compile the binaries with gyp and then push them to Github as release artifacts.

https://github.com/ranisalt/node-argon2/blob/ff9a0029cc12c414951b55850c2bfe8797b9159b/package.json#L64-L65

Then on installation node-pre-gyp will fetch the binary blob from the Github releases and use it.

What I'm missing is some sort of hashes we check during installation (or better signing), to make sure the binaries were not tampered with. Right now anyone with permissions for this repository can just re-upload a custom binary and users will get that on next installation.

This seems to be related: https://github.com/mapbox/node-pre-gyp/issues/358

Also non-deterministic builds make it even harder to trust pre-built binaries https://github.com/ranisalt/node-argon2/issues/206

Should we educate users about this risk in the readme? And should we recommend always building from source? Interested to hear your thoughts on this. Thanks! :hugs:

**Comment by BjornLuG** [comment]
I guess it's fair to add information about the prebuilt binaries in the README and always recommend building them from source. Currently, the prebuilt binaries are only published from [GitHub Actions](https://github.com/ranisalt/node-argon2/actions) but who knows if the author would one day do something malicious by tampering the releases :P 

As for checksums/hash check, there doesn't seem to be an easy way to do so. The GitHub release API also [doesn't have a way of providing the hash](https://stackoverflow.com/questions/29671303/where-to-get-md5-hashes-from-a-github-release) yet.

I could send a PR during my free time about the prebuilt binaries. `node-argon2` also recently dropped support for node 8.x so that would need to be updated too.

**Comment by ranisalt** [comment]
> `-argon2` also recently dropped support for node 8.x so that would need to be updated too.

We strictly follow the Node LTS release, and 8.x is past EOL so I dropped testing. It should work just fine, if the user insists.

**Comment by ranisalt** [comment]
Closed by #247
