### ISSUE TITLE
Make synchronous call function available

### ISSUE THREAD

**Issue by eisenhaus335** [ranisalt/node-argon2#254]
hello
i want to write library javascript before but unable to do so cause argon2 just returning promise first rather than an value. is there any way to call hash function with synchronous manner? 
already search how to convert async into sync function but not found anything useful

**Comment by ranisalt** [comment]
No, it's not feasible since Argon2 is slow and it will lock up your main thread. Use async/await or at least .then the return value.

**Comment by eisenhaus335** [comment]
ok thanks. i just realize how to async and sync. its just i am not understand much about sync. gotta close this issue

**Comment by timvol** [comment]
I don't want open a separate ticket because I also need the synchronous functions. I wrote an argon2 type for mongoose. Unfortunately mongoose doesn't support Promises / async/await for getters. Hence I'm using the very old 0.11.1 version which is the latest version that exposes the synchronous functions for my plugin. That's not optimal...
At first I tried to use 0.8.0 because 0.11.1 prints some warnings on the console (bad for a productive version). After some testing I figured out that 0.8.0 isn't compatible to at least Node.js 12.13. So I tried other versions... Version 0.9.0 does not compile on Windows and if I remember correctly 0.10.0 already prints some warnings regarding the deprecation of the synchronous API. The solution atm is to overwrite the console.warn() to suppress these warnings right before hashSync() call and restore to original function afterwards.
So, maybe we can add support for the synchronous API again? I mean... yes, it might lock the main thread but I'm aware of it and I don't like to use the mongoose hooks for encryption. Otherwise I hope that mongoose add support for async/await getters (but that's not up to the argon2 project).

**Comment by ranisalt** [comment]
@timvol would a callback version suit? Usually libraries using outdated patterns accept callbacks, in that case you can use [callbackify](https://nodejs.org/api/util.html#util_util_callbackify_original).

**Comment by timvol** [comment]
Thank you @ranisalt but unfortunately I see no change/idea how they can solve the problem. My implementation is like the following:

```js
class Argon2 extends mongoose.SchemaType {
  constructor (name, opts) {
    // ...
  }

  cast (value) {
    const warn = console.warn
    console.warn = () => {}
    const result = argon2.hashSync(value)
    console.warn = warn

    return result
  }
}
```
The cast() function is called by mongoose and in this function I need to do the hashing. I already tried to simply return the promise to mongoose but what I got was a pending Promise. So mongoose didn't wait for the promise to be resolved.

**Comment by Coinhexa** [comment]
> No, it's not feasible since Argon2 is slow and it will lock up your main thread. Use async/await or at least .then the return value.

How come bcrypt has a hashSync method but argon2 doesnt? Surely bcrypt also locks the main thread when you salt 14 rounds

**Comment by ranisalt** [comment]
@Coinhexa they [duplicate the code](https://github.com/kelektiv/node.bcrypt.js/blob/master/src/bcrypt_node.cc#L166-L195) to achieve that.

If you insist, you can use [deasync](https://www.npmjs.com/package/deasync)
