### ISSUE TITLE
argon2 format details requested

### ISSUE THREAD

**Issue by j3g** [ranisalt/node-argon2#285]
Hey All :)  I'm finding it frustrating that this project and the related project do not document the output. For example:
`"$argon2id$v=19$m=4096,t=3,p=1$B5CnWTSgIfRvQJlhgjW2Pg$U4Mi9uM7y8rP3pYtVO3vRKKtoUK8VA/F32zBCVc82AA"`

After some research I've found that you are base64 encoding the output. It would be helpful to mention the output format in this project, and be specific about the underlining projects output (which is a binary value depending on the hash size requested)

Thanks!

**Comment by ranisalt** [comment]
Why is it relevant to you?

Note that the hash format follows the [PHC string format](https://github.com/P-H-C/phc-string-format/blob/master/phc-sf-spec.md), it is unrelated to Argon2.

**Comment by j3g** [comment]
Thanks for the education. This is exactly what I was looking for. I had to find the information from some random blog. Would be great to link this to the README. I'm just a security researcher learning. Thank you.

**Comment by ranisalt** [comment]
> I'm just a security researcher learning

Ah, that's perfect :) the repository for Argon2 is not the most organized one, especially since it was never properly standardized, and that makes it hard for anyone trying to learn, indeed.

You can find more information in the [`@phc/format`](https://github.com/simonepri/phc-format#readme) package, if you prefer to see code rather than technical specs.

**Comment by RichCerone** [comment]
To add to this question for the format: Is it considered good practice to store the entire string format in a database? For example if I was encrypting passwords and stored the entire string: $argon2id$v=19$m=4096,t=3,p=1$B5CnWTSgIfRvQJlhgjW2Pg$U4Mi9uM7y8rP3pYtVO3vRKKtoUK8VA/F32zBCVc82AA
would this be considered bad practice since I am giving away some indication of how the string was encrypted?

**Comment by ranisalt** [comment]
@RichCerone no, you can not restore the plain text password (called preimage) from the hash, no matter how much information you provide. Argon2 is what we call an one-way function, so you need the plain text again to generate the same output hash.

You *MUST* store the parameters to be able to verify a password. You need to provide the very same parameters again (version, costs and salt) to be able to verify, so it's not only good practice, it's a requirement to store the parameters somewhere.

**Comment by RichCerone** [comment]
Excellent, just wanted to make sure sorting the parameters with the hash is the way to go!

**Comment by j3g** [comment]
hey @ranisalt, I'm designing some new crypto systems. And this is the first i'm seeing of this string format to describe the operations of the cipher. I would like to use a similar format for my research purposes. I understand in this instance we are talking about PHC, which is for hashes. Have you seen this string format used for encryption algorithms? I have not, that's why I ask. Thanks!

**Comment by ranisalt** [comment]
> Have you seen this string format used for encryption algorithms?

No, and it's probably not useful. With encryption, you have to know the keys too, so you already know beforehand algorithm type and whatever parameters have been used.
