### ISSUE TITLE
argon2 invalid ELF header on WSL

### ISSUE THREAD

**Issue by Gers2017** [ranisalt/node-argon2#324]
### Steps to reproduce
1. open a wsl terminal
2. run yarn add --save argon2
3. import argon2 at the top of the file
4. run ts-node index.ts (run the ts file with ts-node-dev or ts-node)

My [tsconfig](https://pastebin.com/gNa2MRRE)
Using `"argon2": "^0.28.2"` on node `v16.13.0`, typescript `4.2.4`, yarn `v1.22.15`

### Expected behaviour
Run the server without any errors. Hash some data to store it on a database
I tried to do the same without WSL and it works fine.

### Actual behaviour
Unable to properly run the server. Instead I got this error
````bash
Error: /mnt/c/Users/Gers2/code/node.js/@cute-devs-petite/cute-devs-server/node_modules/argon2/lib/binding/napi-v3/argon2.node: invalid ELF header
    at Module._extensions..node (node:internal/modules/cjs/loader:1183:18)
    at Object.nodeDevHook [as .node] (/mnt/c/Users/Gers2/code/node.js/@cute-devs-petite/cute-devs-server/node_modules/ts-node-dev/lib/hook.js:63:13)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/mnt/c/Users/Gers2/code/node.js/@cute-devs-petite/cute-devs-server/node_modules/argon2/argon2.js:9:56)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Module._compile (/mnt/c/Users/Gers2/code/node.js/@cute-devs-petite/cute-devs-server/node_modules/source-map-support/source-map-support.js:568:25)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
[ERROR] 12:26:23 Error: /mnt/c/Users/Gers2/code/node.js/@cute-devs-petite/cute-devs-server/node_modules/argon2/lib/binding/napi-v3/argon2.node: invalid ELF header
````

### Environment
**Windows 10 with WSL**:

**Node version:**
`v16.13.0`
**Compiler version:**

**Comment by sugamkarki** [comment]
@Gers2017  Run ```npm install``` again. This solved my error.

**Comment by mnts-i** [comment]
I have the same problem.

I think the problem arises because you `npm install` in your Windows console and so it builds the binary for the Windows BUT NodeJS image uses a Linux distro. I tried to solve this by npm installing `@node-rs/argon2` and then by npm installing `@node-rs/argon2-linux-x64-gnu` which has the prebuilt binaries for my NodeJS (Debian) image. 

Unfortunately npm during `@node-rs/argon2-linux-x64-gnu` installation throws the following error: `Unsupported platform for @node-rs/argon2-linux-x64-gnu@1.1.0: wanted {"os":"linux","arch":"x64"} (current: {"os":"win32","arch":"x64"})`. I don't know if there is a solution to bypass this check though so I am stuck as well.

**Comment by ranisalt** [comment]
Are you by any change installing inside WSL and then trying to run it outside WSL?

That would install the Linux version of the prebuilt binaries from WSL, which will not load under Node on Windows (i.e. outside WSL)

**Comment by sugamkarki** [comment]
That is precisely what caused the problem. Thank you!

**Comment by jdgregson** [comment]
I was getting this error because the version of `npm` I was running was installed on Windows. I just fired up WSL and ran `npm install` without realizing that I had not installed `npm` or `nodejs` inside of WSL yet.

If you're still getting this after trying the above, try running `sudo apt-get update && sudo apt-get install npm nodejs && npm install` in WSL.

**Comment by Adebisi01** [comment]
On my own end after running docker-compose build --no-cache , to run npm install without cache. Issue still persist
Issue was mainly due to my volume mounting my current directory to the /app on the container . 
i solved it by doing 
volume:
    - ./src : /app/src
    
 that way node_modules was not mounted after being ignored
