### ISSUE TITLE
Implement bcrypt's genSalt with iterations

### ISSUE THREAD

**Issue by ahkhanjani** [ranisalt/node-argon2#353]
Currently I have to use both libraries to achieve the balance which is very awkward. Please consider adding an exported salt generator or at least an iteration or cost option.

**Comment by ranisalt** [comment]
What is the point of that function?

We use [`crypto.randomBytes`](https://nodejs.org/api/crypto.html#cryptorandombytessize-callback), which is cryptographically strong and enough for password hashing.

It looks like [what bcrypt uses as "iterations" for generating a salt](https://github.com/kelektiv/node.bcrypt.js#a-note-on-rounds) is functionally equivalent to [argon2 time cost](https://github.com/ranisalt/node-argon2/wiki/Options#timecost), which you can specify with `timeCost`.

Note that you shouldn't be choosing your own salts, unless you are absolutely sure you know the implications and must do that.

**Comment by ahkhanjani** [comment]
Thank you. I simply didn't know about timeCost.
If it's the same as bcrypt in this matter, why is default value so low as 3 while bcrypt allows the minimum of 8? Or does argon2 have a different measurement for this value?

**Comment by ranisalt** [comment]
Yes, the numbers aren't comparable. So much so, that in bcrypt it is an exponent (i.e. 8 actually means 2^8 iterations), while for Argon2 it is linear.

We chose 3 as the default because it is the recommended value [in the published RFC](https://datatracker.ietf.org/doc/rfc9106/)  - read to section 4, (Parameter Choice), and notewe are using the SECOND RECOMMENDED option because Node limits the amount of memory that can be allocated. It should be strong enough for password hashing.

If you want to improve on that, you can follow the procedure from step 3 and find a configuration stronger than the default. In short, you want to set `parallelism` to how many cores your machine has, increase the `memoryCost` to as much as you can spare, and find the highest value for `timeCost` that is fast enough for your use case.

[`argon2themax`](https://www.npmjs.com/package/argon2themax) automates that procedure, though it hasn't been updated in a while. cc @jdconley

**Comment by ahkhanjani** [comment]
Thank you for your complete answer. It's truly appreciated.
Best Regards

**Comment by jdconley** [comment]
> [`argon2themax`](https://www.npmjs.com/package/argon2themax) automates that procedure, though it hasn't been updated in a while. cc @jdconley

Thanks for the mention! I didn't get nearly as much interest in that project as I thought. I think people don't quite see the value in future proofing hashes, or primarily use SaaS account services for new projects now. 🤷 Happy to take PR's to update the project.

**Comment by ahkhanjani** [comment]
> 🤷 Happy to take PR's to update the project.

@jdconley Hi. I would love to contribute to the project!
