### ISSUE TITLE
Mismatched output between v0.28.7 and v0.30.2 ?

### ISSUE THREAD

**Issue by knightcode** [ranisalt/node-argon2#363]
Just wondering if there's something we need to change in our code when upgrading from 0.28.7 to 0.30.2. After upgrading and changing nothing else in our code, we're getting password mismatches. Is this intended? We could conduct a migration, we'd need to have both versions installed at the same time.

### Steps to reproduce
1. Start with argon2@0.28.7
2. run `npm install argon2@latest`

### Expected behaviour
Previously stored hashed passwords should still match newly hashed passwords.

### Actual behaviour
The output of the updated library isn't matching the hashed data stored in our db.

### Environment
**Operating system**: Mac OS 13.0

**Node version:** 16.18.0

**Compiler version:** gcc (Apple clang version 14.0.0 via Xcode)

**Comment by ranisalt** [comment]
Between these versions, the default parameters have been increased - the Argon2 RFC was published with higher recommended cost.

It should only be an issue i you are comparing hashes with eachother - which will fail because the parameters have changed -, instead of using the `verify` function - which will be correct because `verify` is aware of the parameters of the hash you are trying to check.

If that is the case, replace in your code:

```js
const hashed = await argon2.hash(password)
if (hashed === storedPassword) {
  ...
}
```

with

```js
if (await argon2.verify(storedPassord, password)) {
  // password match
} else {
  // password did not match
}
```

[as described here](https://github.com/ranisalt/node-argon2#usage)

**Comment by knightcode** [comment]
@ranisalt Thanks! ...`verify()` expects a string as it's first argument, but `hash()` outputs a Buffer. Should the buffer be hex or base64 encoded before being passed to `verify()`. I can't find this documented anywhere. ...Or is the typescript def just mistake, and it actually can receive a Buffer?

**Comment by knightcode** [comment]
Actually, passing the Buffer and using any of the buffer->string encoding options are failing for me. I'm getting this error from the verify call:
```
error: terminating due to unhandled error: pchstr must contain a $ as first char TypeError: pchstr must contain a $ as first char
    at deserialize (/System/Volumes/Data/docs/seccom/scserver/node_modules/@phc/format/index.js:147:11)
    at Object.verify (/System/Volumes/Data/docs/seccom/scserver/node_modules/argon2/argon2.js:88:15)
```
This is our implementation:
```ts
  const pepper = ...;
  const hmac = crypto.createHmac("sha512", pepper);
  hmac.update(password);
  return argon2.hash(hmac.digest(), {
    type: argon2.argon2id,
    raw: true,
    salt: salt,
    memoryCost: 15360
  });
```
```ts
  const pepper = ...;
  const hmac = crypto.createHmac("sha512", pepper);
  hmac.update(password);
  const peppered = hmac.digest();
  return argon2.verify(storedHash.toString("base64"), peppered, {
    type: argon2.argon2id,
    raw: true,
    salt: salt,
    memoryCost: 15360
  });
```
Is this due to the `raw` option? How do I correct for that?

Btw, as the text I'm printing with the error suggests, it escaped the try/catch block that was surrounding the verify() call. This usually happens because of some faulty or missing compiler flags passed to node-gyp or wasm builds. This is a major stability issue for server code.  ...I've got my global unhandled exception handlers in place before importing argon2 specifically for this reason. But, if you build is depending on global exception handling for something particular, it won't get called.

**Comment by knightcode** [comment]
@ranisalt any suggestions?

**Comment by ranisalt** [comment]
Sorry for the delay, I am currently on vacation.

I see that you are passing a lot of parameters that should not be messed with unless you know what you are doing and what they do, which does not seem to be the case. Raw output is one of them, and custom salt is another - you are weakening your own security by doing so.

You should be able to correct your own stored passwords by using [@phc/format like we do here](https://github.com/ranisalt/node-argon2/blob/master/argon2.js#L60-L74), passing the raw hash, the stored salt and the parameters you manually set, to generate an encoded hash that can be used with `verify`. Note that the encoded hash is longer, so you might need to change your database column length.

**Comment by knightcode** [comment]
I don't see anything that makes it less safe. And we're not going to incur the added processing and storage costs of base64 encoding.... for no benefit. For millions of users, that's a big cost increase. I get, though, that it's somewhat of a bridge too far to ask us to store multiple fields for passwords, especially when trying to get people to migrate. It's better to just tell us to suck it up and take the bloat. But I'm willing to do the extra work here. As such, it seems like `parallelism` increases from 1 to 4, `memoryCost` increases from 4096 to 65536, and `timeCost` stays at 3. Am I correct?

If using the old values will work with the updated library, I'll migrate our users to the new values over time.

I guess, then, the one request would be just to publish changes to the default values in the README. They are part of the public-facing API.

**Comment by ranisalt** [comment]
> I don't see anything that makes it less safe

It would be the same unless you are using a cryptographically safe random generator - for Node, that would be `crypto.randomBytes`, which is already what this library uses, so using custom salts will not add any safety.

I noticed, however, that a custom salt must be passed whenever you use raw output, because you can not extract the salt from the raw output, and I will fix that in the documentation.

> And we're not going to incur the added processing and storage costs of base64 encoding.... for no benefit. For millions of users, that's a big cost increase.

For 100 million users, increasing from the default 32 byte raw hash to 97 encoded bytes, though you probably make much more money than the few extra dollars an extra 65 GB might cost. I really don't think you can measure a significant difference of "processing" the raw output into an encoded hash, though.

I get that you want to save those few bucks, and you should be able to do as you wish. You should either store the parameters separately, or lock defaults to never change them. This indeed needs to be clarified in the documentation, as you mention later.

> As such, it seems like `parallelism` increases from 1 to 4, `memoryCost` increases from 4096 to 65536, and `timeCost` stays at 3. Am I correct?

Yes, that's correct. Since you are there already, you can tweak these parameters to use higher values for forward safety.

You certainly know that, but for future users: the very same input parameters will always generate the very same hash. The safety against rainbow tables is obtained by using different salts for each password (the default), so that two users with the same password will get different hashes.
