### ISSUE TITLE
Argoon2 is weaker than bcrypt at runtimes < 1000 ms

### ISSUE THREAD

**Issue by ZiiMakc** [ranisalt/node-argon2#373]
Investigating password hashing algorithms I saw a comment [about Argon2](https://twitter.com/TerahashCorp/status/1155129705034653698)
> not to use Argon2 for password hashing. It is weaker than bcrypt at runtimes < 1000 ms.

I would like to know what exactly does it mean and what password hashing algorithm for general usage is better to pick or what settings to use for argon2?

Questions:
1) Does Argon2 is worse than bcrypt at runtimes < 1000 ms?
2) Does 1000ms means that Argon2 validate hash and hash operations should take more than 1 second to be better than bcrypt?
3) What settings for Argon2 to use to achieve 1 second timecost? Explanation for each setting will be nice.
4) Should I pick Argon2 for general password hashing for general web application?
5) If we look at this [setting recommendation](https://security.stackexchange.com/questions/193351/in-2018-what-is-the-recommended-hash-to-store-passwords-bcrypt-scrypt-argon2) that is approximately 2000ms
-512MB of memory
-8 iterations
-Parallelism factor of 8
Does this mean that each user login will take 2 seconds and described amount of memory? What if 10 users will log in at the same time, will the last one wait for ~10 seconds if I have 1GB of ram?

**Comment by ranisalt** [comment]
> Does Argon2 is worse than bcrypt at runtimes < 1000 ms?

The only sources I found claiming that were tweets, or pages referring to those tweets. So it depends on who you choose to trust. You don't have to change algorithms, just increase the parameters if you don't feel safe.

> Does 1000ms means that Argon2 validate hash and hash operations should take more than 1 second to be better than bcrypt?

It refers to hashing the password. Verifying is just hashing with the same parameters and comparing, so it should also take roughly the same amount of time.

> What settings for Argon2 to use to achieve 1 second timecost? Explanation for each setting will be nice.

It depends on your machine. The Argon2 RFC has [a section on choosing optimal parameters](https://www.rfc-editor.org/rfc/rfc9106.html#name-parameter-choice), or you can use [argon2themax](https://www.npmjs.com/package/argon2themax) which will try to find it.

We have documentation in each possible parameter [in this repository's wiki](https://github.com/ranisalt/node-argon2/wiki/Options), but you should look into maximizing time cost, then memory cost.

> Should I pick Argon2 for general password hashing for general web application?

Yes, but if you are already using bcrypt, you don't have to change, it is still safe for years to come.

> Does this mean that each user login will take 2 seconds and described amount of memory? What if 10 users will log in at the same time, will the last one wait for ~10 seconds if I have 1GB of ram?

Again, you have to test, it depends on the processor. A parallelism factor of 8 will be slow on a 4-core processor because it will have to context switch a lot, for example. Following the recommended steps to choose parameters, as I linked above, is the way to go.

[The defaults in this repository](https://github.com/ranisalt/node-argon2/blob/master/argon2.js#L15-L23) follow the **SECOND RECOMMENDED** default choice from the RFC because there is a limit in Node.js that does not allow the interpreter to allocate more than 1 GB in total. You can increase the memory cost up to 19 or 20 (not sure), and the time cost to your liking.

The time each user will wait depends on your processor, if you are hashing with 4 threads, and you have 64 cores it is more than enough. It also depends on the scheduler to distribute processor time for each hashing job.

Hope that clears up! Feel free to follow up if you are still in doubt.
