### ISSUE TITLE
Hash in .Net and Verify in node.js

### ISSUE THREAD

**Issue by intrida-dev** [ranisalt/node-argon2#384]
I have a query that can I use .Net to hash + salt passwords and store them in database. We want to verify the password in node.js. The hashed passwords and salt keys are stored as base64 strings in database.
Please let us know how can we achieve hashing in .Net and verifying in node.js code.

**Comment by ranisalt** [comment]
What library are you using to hash in .NET? Ideally, the generated hash already contains the salt and is in base64 so you shouldn't need this step. If you are using [Konscious.Security.Cryptography](https://github.com/kmaragon/Konscious.Security.Cryptography) with the recommended usage, just plug the generated hash to the `verify` function of node-argon2 and it will return either true or false.

**Comment by intrida-dev** [comment]
We are using 'Konscious.Security.Cryptography.Argon2'. Now we are able to verify the password(hashed in .Net) in node.js using node-argon2. Not problem is other way. When we hash from node.js and try to verify in .Net, it doesn't work.

**Comment by ranisalt** [comment]
I found kmaragon/Konscious.Security.Cryptography#21 and it seems the author did not include a `verify` function that you can use. The reason seems incorrect (it is not more or less secure to include the parameters in the hash, in fact you *should* use the PHC format).

We use the [PHC string format](https://github.com/P-H-C/phc-string-format/blob/master/phc-sf-spec.md) as recommended, which means encoded hashes have the following format:

```
$argon2id$v=19$m=65536,t=3,p=4$c2FsdHNhbHRzYWx0c2FsdA$rBWULD5jOGpQy32rLvGcmvQMVqIVNAmrCtekWvUA8bw
```

That is

```$<function>$<params>$<salt, base64 encoded>$<hash, base64 encoded>```

So what you can do from your side is split on the `$` character to get the parts of the encoded hash, pass it to the `Hash` function from `Konscious.Security.Cryptography.Argon2` and then compare the resulting hash, since the same parameters result in the same hash always.

Let me know if you need more help. I also suggest opening an issue upstream at kmaragon/Konscious.Security.Cryptography to request a `verify` function to be implemented, as it improves developer experience.

**Comment by intrida-dev** [comment]
Thanks for your reply, @ranisalt.

It seems like 'same parameters result in the same has always' is true for that language. I can see that .Net generates different hash than node.js with same parameters.

I am attaching the node.js and .Net sample applications showing the same. Please have a look at them.
Also see the below output screenshots:

.Net:
![image](https://github.com/ranisalt/node-argon2/assets/73640257/244f8da3-00d6-4ad8-b9a4-b27f16ddc55e)

Node.js:
![image](https://github.com/ranisalt/node-argon2/assets/73640257/60532bb0-697f-4182-a8ba-f315b59cb63c)

[Nodejs.zip](https://github.com/ranisalt/node-argon2/files/12213397/Nodejs.zip)

**Comment by ranisalt** [comment]
You likely have a typo in your code. I can see that in Node you are using `64536` for memory cost instead of `65536` like you do on .NET

**Comment by intrida-dev** [comment]
Thanks, @ranisalt. 
We have been debugging this for 2 days and we didn't pay attention toward this small typo. Anyway thanks again for helping us out. :-)
