### ISSUE TITLE
Crash with docker

### ISSUE THREAD

**Issue by hare0319** [ranisalt/node-argon2#397]
Welcome to the issues section if it's your first time!

### Before creating an issue, please be sure to:
- [x] Checkout to the latest version, **including submodules**
- [x] Try to find an *isolated* way to reproduce the behavior
- [x] Fill in all the blanks in the most specific way you can

### Steps to reproduce
1. I've created a [repo](https://github.com/hare0319/argon2_with_docker.git) to reproduce the issue.
2. Once clone the repo, the app can be started with 'npm start'.
3. Build docker image with `docker build .` and start the container with `docker run -itv ./:/app <image> /bin/sh`
4. Start the node app with `npm start`. The app crashes with `Segmentation fault` and exit with 139.

### Expected behaviour
The app can be correctly started on docker container.

### Actual behaviour
Crashes with `Segmentation fault` (139).

After reinstall argon2 package from container, the app can be executed correctly.

I think it works few months before, not quite sure through...

### Environment
**Operating system**: 
OS Name:                   Microsoft Windows 11 Pro
OS Version:                10.0.22631 N/A Build 22631

with wsl:
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy

**Node version:**  v 20.11.1

**Compiler version:**

**Comment by ranisalt** [comment]
This is because your container runs on Alpine, but your local machine likely does not, and in https://github.com/hare0319/argon2_with_docker/blob/1bdbb365ac2ac936e55edb937a84c9c3e64f15d0/Dockerfile#L13 when you `COPY --chown=node:node . .` you are overriding the contents of `node_modules` from the previous invocation of `npm i` with the contents from your local machine, which will copy Argon2 with the specific binary for your machine.

I will change this with the upcoming version 0.40 where it will ship all of the binaries and it can be selected at runtime, since this seems to be a very common misunderstanding. You can try it now with `npm i --save argon2@next` and see if it still happens.

**Comment by hare0319** [comment]
Well, thanks very much for your help, argon2@next works for my case.
